server:
  port: 8081
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/proyecto4
    username: postgres
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
jwt:
  secret: kfndslknfsdZanfsdafoisafewonvvsduovwencinsdqcnweucnwnucwencwnsocnfdsocnsdioancsadncouasdncasdncsandcnsdipcmisadmcoasd
springdoc:
  api-docs:
    path: /v1/api-docs
  swagger-ui:
    path: /swagger-ui/index.html