version: '3'


services:
  db:
    image: postgres:14.3
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: proyecto1
    container_name: proyecto1db
    volumes:
      - ./postgres:/var/lib/postgresql/data