server:
  port: 8084
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/franherran
    username: franherran
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
jwt:
  secret: lkhfiusdfoyuqu9weifjuredshgfhwejkyfhgieywsdjfegrydisuifhhewyousgdfyiwejhksdfghweacdgyujtrhgdfjgjkjdjtfjghfd